<a href="https://colab.research.google.com/github/anila-saju/R-programming/blob/main/world_population.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
install.packages("psych")

Installing package into ‘/usr/local/lib/R/site-library’
(as ‘lib’ is unspecified)

also installing the dependencies ‘mnormt’, ‘GPArotation’

In [ ]:
library(psych)

In [35]:
library(psych)
data<-read.csv("world_population.csv")
describe(data)

ERROR: Error in describe(data): could not find function "describe"

In [36]:
# Use the head function to the first 6 row
data<-read.csv("world_population.csv")
head(data, n = 6)

  Rank1 CCA3 Country.Territory Capital          Continent X2022.Population
1  36   AFG                    Kabul            Asia      41128771
2 138   ALB  Albania           Tirana           Europe     2842321
3  34   DZA  Algeria           Algiers          Africa    44903225
4 213   ASM  American Samoa    Pago Pago        Oceania      44273
5 203   AND  Andorra           Andorra la Vella Europe       79824
6  42   AGO  Angola            Luanda           Africa    35588987
  X2020.Population X2015.Population X2010.Population X2000.Population
1 38972230         33753499         28189672         19542982
2  2866849          2882481          2913399          3182021
3 43451666         39543154         35856344         30774621
4    46189            51368            54849            58230
5    77700            71746            71519            66097
6 33428485         28127721         23364185         16394062
  X1990.Population X1980.Population X1970.Population Area..km..
1 10694796         12486631         10752971          652230
2  3295066          2941651          2324731           28748
3 25518074         18739378         13795915         2381741
4    47818            32886            27075             199
5    53569            35611            19860             468
6 11828638          8330047          6029700         1246700
  Density..per.km.. Growth.Rate World.Population.Percentage
1  63.0587              NA      0.52
2  98.8702          0.9957      0.04
3  18.8531          1.0164      0.56
4 222.4774          0.9831      0.00
5 170.5641          1.0100      0.00
6  28.5466          1.0315      0.45

In [ ]:
# Use the tail function to get the last 6 rows
data<-read.csv("world_population.csv")
tail(data, n = 6)

    Rank CCA3 Country.Territory Capital  Continent X2022.Population
229  16  VNM  Vietnam           Hanoi    Asia      98186856
230 226  WLF  Wallis and Futuna Mata-Utu Oceania      11572
231 172  ESH  Western Sahara    El Aaiún Africa      575986
232  46  YEM  Yemen             Sanaa    Asia      33696614
233  63  ZMB  Zambia            Lusaka   Africa    20017675
234  74  ZWE  Zimbabwe          Harare   Africa    16320537
    X2020.Population X2015.Population X2010.Population X2000.Population
229 96648685         92191398         87411012         79001142
230    11655            12182            13142            14723
231   556048           491824           413296           270375
232 32284046         28516545         24743946         18628700
233 18927715         16248230         13792086          9891136
234 15669666         14154937         12839771         11834676
    X1990.Population X1980.Population X1970.Population Area..km..
229 66912613         52968270         41928849         331212
230    13454            11315             9377            142
231   178529           116775            76371         266000
232 13375121          9204938          6843607         527968
233  7686401          5720438          4281671         752612
234 10113893          7049926          5202918         390757
    Density..per.km.. Growth.Rate World.Population.Percentage
229 296.4472          1.0074      1.23
230  81.4930          0.9953      0.00
231   2.1654          1.0184      0.01
232  63.8232          1.0217      0.42
233  26.5976          1.0280      0.25
234  41.7665          1.0204      0.20

In [ ]:
# How do you ge the average in 2010
data<-read.csv("world_population.csv")
average_2010 <- mean(data$X2010.Population, na.rm = TRUE)
print(average_2010)

[1] 29845235

In [ ]:
# Get the first country based on rank
data<-read.csv("world_population.csv")
df<-data[order(data$Rank), ]
rank <- df[1, ]
print(rank)

   Rank CCA3 Country.Territory Capital Continent X2022.Population
42    1  CHN             China Beijing      Asia       1425887337
   X2020.Population X2015.Population X2010.Population X2000.Population
42       1424929781       1393715448       1348191368       1264099069
   X1990.Population X1980.Population X1970.Population Area..km..
42       1153704252        982372466        822534450    9706961
   Density..per.km.. Growth.Rate World.Population.Percentage
42          146.8933           1                       17.88

In [ ]:
# Get the last country based on rank
data<-read.csv("world_population.csv")
df<-data[order(data$Rank), ]
rank <- df[nrow(df), ]
print(rank)

    Rank CCA3 Country.Territory      Capital Continent X2022.Population
227  234  VAT      Vatican City Vatican City    Europe              510
    X2020.Population X2015.Population X2010.Population X2000.Population
227              520              564              596              651
    X1990.Population X1980.Population X1970.Population Area..km..
227              700              733              752          1
    Density..per.km.. Growth.Rate World.Population.Percentage
227               510       0.998                           0

In [ ]:
df <- read.csv("world_population.csv")
str(df)

'data.frame':	234 obs. of  17 variables:
 $ Rank                       : int  36 138 34 213 203 42 224 201 33 140 ...
 $ CCA3                       : chr  "AFG" "ALB" "DZA" "ASM" ...
 $ Country.Territory          : chr  "" "Albania" "Algeria" "American Samoa" ...
 $ Capital                    : chr  "Kabul" "Tirana" "Algiers" "Pago Pago" ...
 $ Continent                  : chr  "Asia" "Europe" "Africa" "Oceania" ...
 $ X2022.Population           : int  41128771 2842321 44903225 44273 79824 35588987 15857 93763 45510318 2780469 ...
 $ X2020.Population           : int  38972230 2866849 43451666 46189 77700 33428485 15585 92664 45036032 2805608 ...
 $ X2015.Population           : int  33753499 2882481 39543154 51368 71746 28127721 14525 89941 43257065 2878595 ...
 $ X2010.Population           : int  28189672 2913399 35856344 54849 71519 23364185 13172 85695 41100123 2946293 ...
 $ X2000.Population           : int  19542982 3182021 30774621 58230 66097 16394062 11047 75055 37070774 3168523 ...
 $ X1990.Population           : int  10694796 3295066 25518074 47818 53569 11828638 8316 63328 32637657 3556539 ...
 $ X1980.Population           : int  12486631 2941651 18739378 32886 35611 8330047 6560 64888 28024803 3135123 ...
 $ X1970.Population           : int  10752971 2324731 13795915 27075 19860 6029700 6283 64516 23842803 2534377 ...
 $ Area..km..                 : int  652230 28748 2381741 199 468 1246700 91 442 2780400 29743 ...
 $ Density..per.km..          : num  63.1 98.9 18.9 222.5 170.6 ...
 $ Growth.Rate                : num  NA 0.996 1.016 0.983 1.01 ...
 $ World.Population.Percentage: num  0.52 0.04 0.56 0 0 0.45 0 0 0.57 0.03 ...

In [ ]:
df <- read.csv("world_population.csv")
dim(df)

[1] 234  17

In [ ]:
df <- read.csv("world_population.csv")
# nrow(df)
# ncol(df)
# colnames(df)
rownames(df)

  [1] "1"   "2"   "3"   "4"   "5"   "6"   "7"   "8"   "9"   "10"  "11"  "12"
 [13] "13"  "14"  "15"  "16"  "17"  "18"  "19"  "20"  "21"  "22"  "23"  "24"
 [25] "25"  "26"  "27"  "28"  "29"  "30"  "31"  "32"  "33"  "34"  "35"  "36"
 [37] "37"  "38"  "39"  "40"  "41"  "42"  "43"  "44"  "45"  "46"  "47"  "48"
 [49] "49"  "50"  "51"  "52"  "53"  "54"  "55"  "56"  "57"  "58"  "59"  "60"
 [61] "61"  "62"  "63"  "64"  "65"  "66"  "67"  "68"  "69"  "70"  "71"  "72"
 [73] "73"  "74"  "75"  "76"  "77"  "78"  "79"  "80"  "81"  "82"  "83"  "84"
 [85] "85"  "86"  "87"  "88"  "89"  "90"  "91"  "92"  "93"  "94"  "95"  "96"
 [97] "97"  "98"  "99"  "100" "101" "102" "103" "104" "105" "106" "107" "108"
[109] "109" "110" "111" "112" "113" "114" "115" "116" "117" "118" "119" "120"
[121] "121" "122" "123" "124" "125" "126" "127" "128" "129" "130" "131" "132"
[133] "133" "134" "135" "136" "137" "138" "139" "140" "141" "142" "143" "144"
[145] "145" "146" "147" "148" "149" "150" "151" "152" "153" "154" "155" "156"
[157] "157" "158" "159" "160" "161" "162" "163" "164" "165" "166" "167" "168"
[169] "169" "170" "171" "172" "173" "174" "175" "176" "177" "178" "179" "180"
[181] "181" "182" "183" "184" "185" "186" "187" "188" "189" "190" "191" "192"
[193] "193" "194" "195" "196" "197" "198" "199" "200" "201" "202" "203" "204"
[205] "205" "206" "207" "208" "209" "210" "211" "212" "213" "214" "215" "216"
[217] "217" "218" "219" "220" "221" "222" "223" "224" "225" "226" "227" "228"
[229] "229" "230" "231" "232" "233" "234"

In [ ]:
# df <- read.csv("world_population.csv")
# df <- matrix( c('a','a','b','c','b','a'), nrow=2,ncol=3,byrow = TRUE)
# # class(df)
df <- read.csv("world_population.csv")
typeof(df)

[1] "list"

In [ ]:
df <- read.csv("world_population.csv")
subset(df, Rank < 10 & Capital == "Dhaka", select = c("Rank", "Capital", "Continent"))

   Rank Capital Continent
17 8    Dhaka   Asia

In [ ]:
library(dplyr)
df <- read.csv("world_population.csv")
# df
filter(df, Rank < 10)

  Rank CCA3 Country.Territory Capital          Continent     X2022.Population
1 8    BGD  Bangladesh        Dhaka            Asia           171186372
2 7    BRA  Brazil            Brasilia         South America  215313498
3 1    CHN  China             Beijing          Asia          1425887337
4 2    IND  India             New Delhi        Asia          1417173173
5 4    IDN  Indonesia         Jakarta          Asia           275501339
6 6    NGA  Nigeria           Abuja            Africa         218541212
7 5    PAK  Pakistan          Islamabad        Asia           235824862
8 9    RUS  Russia            Moscow           Europe         144713314
9 3    USA  United States     Washington, D.C. North America  338289857
  X2020.Population X2015.Population X2010.Population X2000.Population
1  167420951        157830000        148391139        129193327
2  213196304        205188205        196353492        175873720
3 1424929781       1393715448       1348191368       1264099069
4 1396387127       1322866505       1240613620       1059633675
5  271857970        259091970        244016173        214072421
6  208327405        183995785        160952853        122851984
7  227196741        210969298        194454498        154369924
8  145617329        144668389        143242599        146844839
9  335942003        324607776        311182845        282398554
  X1990.Population X1980.Population X1970.Population Area..km..
1  107147651        83929765         67541860          147570
2  150706446       122288383         96369875         8515767
3 1153704252       982372466        822534450         9706961
4  870452165       696828385        557501301         3287590
5  182159874       148177096        115228394         1904569
6   95214257        72951439         55569264          923768
7  115414069        80624057         59290872          881912
8  148005704       138257420        130093010        17098242
9  248083732       223140018        200328340         9372610
  Density..per.km.. Growth.Rate World.Population.Percentage
1 1160.0350         1.0108       2.15
2   25.2841         1.0046       2.70
3  146.8933         1.0000      17.88
4  431.0675         1.0068      17.77
5  144.6529         1.0064       3.45
6  236.5759         1.0241       2.74
7  267.4018         1.0191       2.96
8    8.4636         0.9973       1.81
9   36.0935         1.0038       4.24

In [ ]:
library(dplyr)
df <- read.csv("world_population.csv")
# df
select(df, Rank, Capital)

    Rank Capital
1    36  Kabul
2   138  Tirana
3    34  Algiers
4   213  Pago Pago
5   203  Andorra la Vella
6    42  Luanda
7   224  The Valley
8   201  Saint John’s
9    33  Buenos Aires
10  140  Yerevan
11  198  Oranjestad
12   55  Canberra
13   99  Vienna
14   91  Baku
15  176  Nassau
16  154  Manama
17    8  Dhaka
18  186  Bridgetown
19   96  Minsk
20   81  Brussels
21  177  Belmopan
22   77  Porto-Novo
23  206  Hamilton
24  165  Thimphu
25   80  Sucre
26  137  Sarajevo
27  144  Gaborone
28    7  Brasilia
29  221  Road Town
30  175  Bandar Seri Begawan
⋮   ⋮    ⋮
205  95  Dushanbe
206  22  Dodoma
207  20  Bangkok
208 155  Dili
209 100  Lomé
210 233  Nukunonu
211 197  Nuku‘alofa
212 153  Port-of-Spain
213  79  Tunis
214  18  Ankara
215 111  Ashgabat
216 212  Cockburn Town
217 227  Funafuti
218  31  Kampala
219  38  Kiev
220  97  Abu Dhabi
221  21  London
222   3  Washington, D.C.
223 200  Charlotte Amalie
224 133  Montevideo
225  43  Tashkent
226 181  Port-Vila
227 234  Vatican City
228  51  Caracas
229  16  Hanoi
230 226  Mata-Utu
231 172  El Aaiún
232  46  Sanaa
233  63  Lusaka
234  74  Harare

In [ ]:
library(dplyr)
df <- read.csv("world_population.csv")
# df
mutate(df, Category=ifelse(Rank <= 100, "Top Class", "Low Class"))

    Rank CCA3 Country.Territory            Capital             Continent
1    36  AFG                               Kabul               Asia
2   138  ALB  Albania                      Tirana              Europe
3    34  DZA  Algeria                      Algiers             Africa
4   213  ASM  American Samoa               Pago Pago           Oceania
5   203  AND  Andorra                      Andorra la Vella    Europe
6    42  AGO  Angola                       Luanda              Africa
7   224  AIA  Anguilla                     The Valley          North America
8   201  ATG  Antigua and Barbuda          Saint John’s        North America
9    33  ARG  Argentina                    Buenos Aires        South America
10  140  ARM  Armenia                      Yerevan             Asia
11  198  ABW  Aruba                        Oranjestad          North America
12   55  AUS  Australia                    Canberra            Oceania
13   99  AUT  Austria                      Vienna              Europe
14   91  AZE  Azerbaijan                   Baku                Asia
15  176  BHS  Bahamas                      Nassau              North America
16  154  BHR  Bahrain                      Manama              Asia
17    8  BGD  Bangladesh                   Dhaka               Asia
18  186  BRB  Barbados                     Bridgetown          North America
19   96  BLR  Belarus                      Minsk               Europe
20   81  BEL  Belgium                      Brussels            Europe
21  177  BLZ  Belize                       Belmopan            North America
22   77  BEN  Benin                        Porto-Novo          Africa
23  206  BMU  Bermuda                      Hamilton            North America
24  165  BTN  Bhutan                       Thimphu             Asia
25   80  BOL  Bolivia                      Sucre               South America
26  137  BIH  Bosnia and Herzegovina       Sarajevo            Europe
27  144  BWA  Botswana                     Gaborone            Africa
28    7  BRA  Brazil                       Brasilia            South America
29  221  VGB  British Virgin Islands       Road Town           North America
30  175  BRN  Brunei                       Bandar Seri Begawan Asia
⋮   ⋮    ⋮    ⋮                            ⋮                   ⋮
205  95  TJK  Tajikistan                   Dushanbe            Asia
206  22  TZA  Tanzania                     Dodoma              Africa
207  20  THA  Thailand                     Bangkok             Asia
208 155  TLS  Timor-Leste                  Dili                Asia
209 100  TGO  Togo                         Lomé                Africa
210 233  TKL  Tokelau                      Nukunonu            Oceania
211 197  TON  Tonga                        Nuku‘alofa          Oceania
212 153  TTO  Trinidad and Tobago          Port-of-Spain       North America
213  79  TUN  Tunisia                      Tunis               Africa
214  18  TUR  Turkey                       Ankara              Asia
215 111  TKM  Turkmenistan                 Ashgabat            Asia
216 212  TCA  Turks and Caicos Islands     Cockburn Town       North America
217 227  TUV  Tuvalu                       Funafuti            Oceania
218  31  UGA  Uganda                       Kampala             Africa
219  38  UKR  Ukraine                      Kiev                Europe
220  97  ARE  United Arab Emirates         Abu Dhabi           Asia
221  21  GBR  United Kingdom               London              Europe
222   3  USA  United States                Washington, D.C.    North America
223 200  VIR  United States Virgin Islands Charlotte Amalie    North America
224 133  URY  Uruguay                      Montevideo          South America
225  43  UZB  Uzbekistan                   Tashkent            Asia
226 181  VUT  Vanuatu                      Port-Vila           Oceania
227 234  VAT  Vatican City                 Vatican City        Europe
228  51  VEN  Venezuela                    Caracas             South America
229  16  VNM  Vietnam                      Hanoi               Asia
230 226  WLF  Wallis and Futuna            Mata-Utu            Oceania
231 172  ESH  Western Sahara               El Aaiún            Africa
232  46  YEM  Yemen                        Sanaa               Asia
233  63  ZMB  Zambia                       Lusaka              Africa
234  74  ZWE  Zimbabwe                     Harare              Africa
    X2022.Population X2020.Population X2015.Population X2010.Population
1    41128771         38972230         33753499         28189672
2     2842321          2866849          2882481          2913399
3    44903225         43451666         39543154         35856344
4       44273            46189            51368            54849
5       79824            77700            71746            71519
6    35588987         33428485         28127721         23364185
7       15857            15585            14525            13172
8       93763            92664            89941            85695
9    45510318         45036032         43257065         41100123
10    2780469          2805608          2878595          2946293
11     106445           106585           104257           100341
12   26177413         25670051         23820236         22019168
13    8939617          8907777          8642421          8362829
14   10358074         10284951          9863480          9237202
15     409984           406471           392697           373272
16    1472233          1477469          1362142          1213645
17  171186372        167420951        157830000        148391139
18     281635           280693           278083           274711
19    9534954          9633740          9700609          9731427
20   11655930         11561717         11248303         10877947
21     405272           394921           359871           322106
22   13352864         12643123         10932783          9445710
23      64184            64031            63144            63447
24     782455           772506           743274           705516
25   12224110         11936162         11090085         10223270
26    3233526          3318407          3524324          3811088
27    2630296          2546402          2305171          2091664
28  215313498        213196304        205188205        196353492
29      31305            30910            29366            27556
30     449002           441725           421437           396053
⋮   ⋮                ⋮                ⋮                ⋮
205   9952787          9543207          8524063          7621779
206  65497748         61704518         52542823         45110527
207  71697030         71475664         70294397         68270489
208   1341296          1299995          1205813          1088486
209   8848699          8442580          7473229          6571855
210      1871             1827             1454             1367
211    106858           105254           106122           107383
212   1531044          1518147          1460177          1410296
213  12356117         12161723         11557779         10895063
214  85341241         84135428         79646178         73195345
215   6430770          6250438          5766431          5267970
216     45703            44276            36538            29726
217     11312            11069            10877            10550
218  47249585         44404611         37477356         32341728
219  39701739         43909666         44982564         45683020
220   9441129          9287289          8916899          8481771
221  67508936         67059474         65224364         62760039
222 338289857        335942003        324607776        311182845
223     99465           100442           102803           106142
224   3422794          3429086          3402818          3352651
225  34627652         33526656         30949417         28614227
226    326740           311685           276438           245453
227       510              520              564              596
228  28301696         28490453         30529716         28715022
229  98186856         96648685         92191398         87411012
230     11572            11655            12182            13142
231    575986           556048           491824           413296
232  33696614         32284046         28516545         24743946
233  20017675         18927715         16248230         13792086
234  16320537         15669666         14154937         12839771
    X2000.Population X1990.Population X1980.Population X1970.Population
1    19542982         10694796         12486631        10752971
2     3182021          3295066          2941651         2324731
3    30774621         25518074         18739378        13795915
4       58230            47818            32886           27075
5       66097            53569            35611           19860
6    16394062         11828638          8330047         6029700
7       11047             8316             6560            6283
8       75055            63328            64888           64516
9    37070774         32637657         28024803        23842803
10    3168523          3556539          3135123         2534377
11      89101            65712            62267           59106
12   19017963         17048003         14706322        12595034
13    8010428          7678729          7547561         7465301
14    8190337          7427836          6383060         5425317
15     325014           270679           223752          179129
16     711442           517418           362595          222555
17  129193327        107147651         83929765        67541860
18     264657           258868           253575          241397
19   10256483         10428525          9817257         9170786
20   10264343          9959560          9828986         9629376
21     240406           182589           145133          120905
22    6998023          5133419          3833939         3023443
23      61371            57470            53565           52019
24     587207           558442           415257          298894
25    8592656          7096194          5736088         4585693
26    4179350          4494310          4199820         3815561
27    1726985          1341474           938578          592244
28  175873720        150706446        122288383        96369875
29      20104            15617            11109            9581
30     333926           261928           187921          133343
⋮   ⋮                ⋮                ⋮                ⋮
205   6272998          5417860          4045965          2993019
206  34463704         26206012         19297659         13618192
207  63066603         55228410         45737753         35791728
208    878360           758106           642224           554021
209   5008035          3875947          2838110          2197383
210      1666             1669             1647             1714
211    102603            98727            96708            86484
212   1332203          1266518          1127852           988890
213   9893316          8440023          6578156          5047404
214  64113547         54324142         44089069         35540990
215   4569132          3720278          2862903          2201432
216     18744            11709             7598             5665
217      9638             9182             7731             5814
218  24020697         17586630         13284026         10317212
219  48879755         51589817         49973920         47279086
220   3275333          1900151          1014048           298084
221  58850043         57210442         56326328         55650166
222 282398554        248083732        223140018        200328340
223    108185           100685            96640            63446
224   3292224          3117012          2953750          2790265
225  24925554         20579100         15947129         12011361
226    192074           150882           118156            87019
227       651              700              733              752
228  24427729         19750579         15210443         11355475
229  79001142         66912613         52968270         41928849
230     14723            13454            11315             9377
231    270375           178529           116775            76371
232  18628700         13375121          9204938          6843607
233   9891136          7686401          5720438          4281671
234  11834676         10113893          7049926          5202918
    Area..km.. Density..per.km.. Growth.Rate World.Population.Percentage
1    652230      63.0587             NA      0.52
2     28748      98.8702         0.9957      0.04
3   2381741      18.8531         1.0164      0.56
4       199     222.4774         0.9831      0.00
5       468     170.5641         1.0100      0.00
6   1246700      28.5466         1.0315      0.45
7        91     174.2527         1.0066      0.00
8       442     212.1335         1.0058      0.00
9   2780400      16.3683         1.0052      0.57
10    29743      93.4831         0.9962      0.03
11      180     591.3611         0.9991      0.00
12  7692024       3.4032         1.0099      0.33
13    83871     106.5877         1.0020      0.11
14    86600     119.6082         1.0044      0.13
15    13943      29.4043         1.0051      0.01
16      765    1924.4876         1.0061      0.02
17   147570    1160.0350         1.0108      2.15
18      430     654.9651         1.0015      0.00
19   207600      45.9295         0.9955      0.12
20    30528     381.8111         1.0038      0.15
21    22966      17.6466         1.0131      0.01
22   112622     118.5635         1.0274      0.17
23       54    1188.5926         1.0000      0.00
24    38394      20.3796         1.0064      0.01
25  1098581      11.1272         1.0120      0.15
26    51209      63.1437         0.9886      0.04
27   582000       4.5194         1.0162      0.03
28  8515767      25.2841         1.0046      2.70
29      151     207.3179         1.0059      0.00
30     5765      77.8841         1.0081      0.01
⋮   ⋮          ⋮                 ⋮           ⋮
205  143100     69.5513          1.0208      0.12
206  945087     69.3034          1.0300      0.82
207  513120    139.7276          1.0013      0.90
208   14874     90.1772          1.0154      0.02
209   56785    155.8281          1.0236      0.11
210      12    155.9167          1.0119      0.00
211     747    143.0495          1.0079      0.00
212    5130    298.4491          1.0035      0.02
213  163610     75.5218          1.0076      0.15
214  783562    108.9145          1.0067      1.07
215  488100     13.1751          1.0140      0.08
216     948     48.2099          1.0131      0.00
217      26    435.0769          1.0096      0.00
218  241550    195.6100          1.0304      0.59
219  603500     65.7858          0.9120      0.50
220   83600    112.9322          1.0081      0.12
221  242900    277.9289          1.0034      0.85
222 9372610     36.0935          1.0038      4.24
223     347    286.6427          0.9937      0.00
224  181034     18.9069          0.9990      0.04
225  447400     77.3975          1.0160      0.43
226   12189     26.8061          1.0238      0.00
227       1    510.0000          0.9980      0.00
228  916445     30.8820          1.0036      0.35
229  331212    296.4472          1.0074      1.23
230     142     81.4930          0.9953      0.00
231  266000      2.1654          1.0184      0.01
232  527968     63.8232          1.0217      0.42
233  752612     26.5976          1.0280      0.25
234  390757     41.7665          1.0204      0.20
    Category
1   Top Class
2   Low Class
3   Top Class
4   Low Class
5   Low Class
6   Top Class
7   Low Class
8   Low Class
9   Top Class
10  Low Class
11  Low Class
12  Top Class
13  Top Class
14  Top Class
15  Low Class
16  Low Class
17  Top Class
18  Low Class
19  Top Class
20  Top Class
21  Low Class
22  Top Class
23  Low Class
24  Low Class
25  Top Class
26  Low Class
27  Low Class
28  Top Class
29  Low Class
30  Low Class
⋮   ⋮
205 Top Class
206 Top Class
207 Top Class
208 Low Class
209 Top Class
210 Low Class
211 Low Class
212 Low Class
213 Top Class
214 Top Class
215 Low Class
216 Low Class
217 Low Class
218 Top Class
219 Top Class
220 Top Class
221 Top Class
222 Top Class
223 Low Class
224 Low Class
225 Top Class
226 Low Class
227 Low Class
228 Top Class
229 Top Class
230 Low Class
231 Low Class
232 Top Class
233 Top Class
234 Top Class

In [ ]:
library(dplyr)
df <- read.csv("world_population.csv")
# df
# arrange(df, Rank)
arrange(df, desc(Rank))

    Rank CCA3 Country.Territory         Capital          Continent
1   234  VAT  Vatican City              Vatican City     Europe
2   233  TKL  Tokelau                   Nukunonu         Oceania
3   232  NIU  Niue                      Alofi            Oceania
4   231  FLK  Falkland Islands          Stanley          South America
5   230  MSR  Montserrat                Brades           North America
6   229  SPM  Saint Pierre and Miquelon Saint-Pierre     North America
7   228  BLM  Saint Barthelemy          Gustavia         North America
8   227  TUV  Tuvalu                    Funafuti         Oceania
9   226  WLF  Wallis and Futuna         Mata-Utu         Oceania
10  225  NRU  Nauru                     Yaren            Oceania
11  224  AIA  Anguilla                  The Valley       North America
12  223  COK  Cook Islands              Avarua           Oceania
13  222  PLW  Palau                     Ngerulmud        Oceania
14  221  VGB  British Virgin Islands    Road Town        North America
15  220  MAF  Saint Martin              Marigot          North America
16  219  GIB  Gibraltar                 Gibraltar        Europe
17  218  SMR  San Marino                San Marino       Europe
18  217  MCO  Monaco                    Monaco           Europe
19  216  LIE  Liechtenstein             Vaduz            Europe
20  215  MHL  Marshall Islands          Majuro           Oceania
21  214  SXM  Sint Maarten              Philipsburg      North America
22  213  ASM  American Samoa            Pago Pago        Oceania
23  212  TCA  Turks and Caicos Islands  Cockburn Town    North America
24  211  KNA  Saint Kitts and Nevis     Basseterre       North America
25  210  NFK  Northern Mariana Islands  Saipan           Oceania
26  209  FRO  Faroe Islands             Tórshavn         Europe
27  208  GRL  Greenland                 Nuuk             North America
28  207  GGY  Guernsey                  Saint Peter Port Europe
29  206  BMU  Bermuda                   Hamilton         North America
30  205  CYM  Cayman Islands            George Town      North America
⋮   ⋮    ⋮    ⋮                         ⋮                ⋮
205 30   ESP  Spain                     Madrid           Europe
206 29   KOR  South Korea               Seoul            Asia
207 28   COL  Colombia                  Bogota           South America
208 27   KEN  Kenya                     Nairobi          Africa
209 26   MMR  Myanmar                   Nay Pyi Taw      Asia
210 25   ITA  Italy                     Rome             Europe
211 24   ZAF  South Africa              Pretoria         Africa
212 23   FRA  France                    Paris            Europe
213 22   TZA  Tanzania                  Dodoma           Africa
214 21   GBR  United Kingdom            London           Europe
215 20   THA  Thailand                  Bangkok          Asia
216 19   DEU  Germany                   Berlin           Europe
217 18   TUR  Turkey                    Ankara           Asia
218 17   IRN  Iran                      Tehran           Asia
219 16   VNM  Vietnam                   Hanoi            Asia
220 15   COD  DR Congo                  Kinshasa         Africa
221 14   EGY  Egypt                     Cairo            Africa
222 13   PHL  Philippines               Manila           Asia
223 12   ETH  Ethiopia                  Addis Ababa      Africa
224 11   JPN  Japan                     Tokyo            Asia
225 10   MEX  Mexico                    Mexico City      North America
226  9   RUS  Russia                    Moscow           Europe
227  8   BGD  Bangladesh                Dhaka            Asia
228  7   BRA  Brazil                    Brasilia         South America
229  6   NGA  Nigeria                   Abuja            Africa
230  5   PAK  Pakistan                  Islamabad        Asia
231  4   IDN  Indonesia                 Jakarta          Asia
232  3   USA  United States             Washington, D.C. North America
233  2   IND  India                     New Delhi        Asia
234  1   CHN  China                     Beijing          Asia
    X2022.Population X2020.Population X2015.Population X2010.Population
1     510              520              564              596
2    1871             1827             1454             1367
3    1934             1942             1847             1812
4    3780             3747             3408             3187
5    4390             4500             5059             4938
6    5862             5906             5978             6052
7   10967            10681             9643             8988
8   11312            11069            10877            10550
9   11572            11655            12182            13142
10  12668            12315            11185            10241
11  15857            15585            14525            13172
12  17011            17029            17695            17212
13  18055            17972            17794            18540
14  31305            30910            29366            27556
15  31791            32552            35020            36458
16  32649            32709            32520            31262
17  33660            34007            33570            31608
18  36469            36922            36760            33178
19  39327            38756            37355            35926
20  41569            43413            49410            53416
21  44175            43621            40205            33034
22  44273            46189            51368            54849
23  45703            44276            36538            29726
24  47657            47642            47790            47403
25  49551            49587            51514            54087
26  53090            52415            48816            48410
27  56466            56026            55895            56351
28  63301            62794            61629            60782
29  64184            64031            63144            63447
30  68706            67311            60911            54074
⋮   ⋮                ⋮                ⋮                ⋮
205   47558630         47363807         46431342         46572772
206   51815810         51844690         50994401         48813042
207   51874024         50930662         47119728         44816108
208   54027487         51985780         46851488         41517895
209   54179306         53423198         51483949         49390988
210   59037474         59500579         60232906         59822450
211   59893885         58801927         55876504         51784921
212   64626628         64480053         63809769         62444567
213   65497748         61704518         52542823         45110527
214   67508936         67059474         65224364         62760039
215   71697030         71475664         70294397         68270489
216   83369843         83328988         82073226         81325090
217   85341241         84135428         79646178         73195345
218   88550570         87290193         81790841         75373855
219   98186856         96648685         92191398         87411012
220   99010212         92853164         78656904         66391257
221  110990103        107465134         97723799         87252413
222  115559009        112190977        103031365         94636700
223  123379924        117190911        102471895         89237791
224  123951692        125244761        127250933        128105431
225  127504125        125998302        120149897        112532401
226  144713314        145617329        144668389        143242599
227  171186372        167420951        157830000        148391139
228  215313498        213196304        205188205        196353492
229  218541212        208327405        183995785        160952853
230  235824862        227196741        210969298        194454498
231  275501339        271857970        259091970        244016173
232  338289857        335942003        324607776        311182845
233 1417173173       1396387127       1322866505       1240613620
234 1425887337       1424929781       1393715448       1348191368
    X2000.Population X1990.Population X1980.Population X1970.Population
1     651              700              733              752
2    1666             1669             1647             1714
3    2074             2533             3637             5185
4    3080             2332             2240             2274
5    5138            10805            11452            11402
6    6274             6324             6106             5537
7    7082             5168             2983             2417
8    9638             9182             7731             5814
9   14723            13454            11315             9377
10  10377             9598             7635             6663
11  11047             8316             6560             6283
12  15897            17123            17651            20470
13  19726            15293            12252            11366
14  20104            15617            11109             9581
15  29610            28127             7776             5802
16  27741            27317            28734            26685
17  26823            23132            21346            18169
18  32465            30329            27076            24270
19  33026            28765            25003            21089
20  54224            46047            31988            23969
21  30489            27845            12243             6260
22  58230            47818            32886            27075
23  18744            11709             7598             5665
24  45461            40636            43097            44968
25  80338            48002            17613            10143
26  45660            47479            43054            38416
27  56184            55599            50106            45434
28  59114            57727            52860            52656
29  61371            57470            53565            52019
30  39658            26027            17100            10533
⋮   ⋮                ⋮                ⋮                ⋮
205   40741651         38889889        37491666         33792617
206   46788591         44120039        38170501         32601143
207   39215135         32601393        26176195         20905254
208   30851606         23162269        16187124         11473087
209   45538332         40099553        33465781         27284112
210   56966397         56756561        56329482         53324036
211   46813266         39877570        29463549         22368306
212   58665453         56412897        53713830         50523586
213   34463704         26206012        19297659         13618192
214   58850043         57210442        56326328         55650166
215   63066603         55228410        45737753         35791728
216   81551677         79370196        77786703         78294583
217   64113547         54324142        44089069         35540990
218   65544383         55793629        38520664         28449705
219   79001142         66912613        52968270         41928849
220   48616317         35987541        26708686         20151733
221   71371371         57214630        43748556         34781986
222   77958223         61558898        48419546         37435586
223   67031867         47878073        34945469         28308246
224  126803861        123686321       117624196        105416839
225   97873442         81720428        67705186         50289306
226  146844839        148005704       138257420        130093010
227  129193327        107147651        83929765         67541860
228  175873720        150706446       122288383         96369875
229  122851984         95214257        72951439         55569264
230  154369924        115414069        80624057         59290872
231  214072421        182159874       148177096        115228394
232  282398554        248083732       223140018        200328340
233 1059633675        870452165       696828385        557501301
234 1264099069       1153704252       982372466        822534450
    Area..km.. Density..per.km.. Growth.Rate World.Population.Percentage
1         1      510.0000        0.9980      0
2        12      155.9167        1.0119      0
3       260        7.4385        0.9985      0
4     12173        0.3105        1.0043      0
5       102       43.0392        0.9939      0
6       242       24.2231        0.9964      0
7        21      522.2381        1.0098      0
8        26      435.0769        1.0096      0
9       142       81.4930        0.9953      0
10       21      603.2381        1.0125      0
11       91      174.2527        1.0066      0
12      236       72.0805        1.0005      0
13      459       39.3355        1.0017      0
14      151      207.3179        1.0059      0
15       53      599.8302        0.9951      0
16        6     5441.5000        0.9994      0
17       61      551.8033        0.9975      0
18        2    18234.5000        0.9941      0
19      160      245.7937        1.0074      0
20      181      229.6630        0.9886      0
21       34     1299.2647        1.0030      0
22      199      222.4774        0.9831      0
23      948       48.2099        1.0131      0
24      261      182.5939        1.0011      0
25      464      106.7909        1.0014      0
26     1393       38.1120        1.0038      0
27  2166086        0.0261        1.0040      0
28       78      811.5513        1.0037      0
29       54     1188.5926        1.0000      0
30      264      260.2500        1.0084      0
⋮   ⋮          ⋮                 ⋮           ⋮
205   505992     93.9909         1.0015       0.60
206   100210    517.0722         0.9997       0.65
207  1141748     45.4339         1.0069       0.65
208   580367     93.0919         1.0193       0.68
209   676578     80.0784         1.0071       0.68
210   301336    195.9191         0.9966       0.74
211  1221037     49.0517         1.0084       0.75
212   551695    117.1419         1.0015       0.81
213   945087     69.3034         1.0300       0.82
214   242900    277.9289         1.0034       0.85
215   513120    139.7276         1.0013       0.90
216   357114    233.4544         0.9995       1.05
217   783562    108.9145         1.0067       1.07
218  1648195     53.7258         1.0071       1.11
219   331212    296.4472         1.0074       1.23
220  2344858     42.2244         1.0325       1.24
221  1002450    110.7188         1.0158       1.39
222   342353    337.5434         1.0147       1.45
223  1104300    111.7268         1.0257       1.55
224   377930    327.9753         0.9947       1.55
225  1964375     64.9082         1.0063       1.60
226 17098242      8.4636         0.9973       1.81
227   147570   1160.0350         1.0108       2.15
228  8515767     25.2841         1.0046       2.70
229   923768    236.5759         1.0241       2.74
230   881912    267.4018         1.0191       2.96
231  1904569    144.6529         1.0064       3.45
232  9372610     36.0935         1.0038       4.24
233  3287590    431.0675         1.0068      17.77
234  9706961    146.8933         1.0000      17.88

In [ ]:
library(dplyr)

data <- read.csv("world_population.csv")

#data <- matrix( c('a','a','b','c','b','a'), nrow=2,ncol=3,byrow = TRUE)
print(group_by(data,Continent))

# A tibble: 234 × 17
# Groups:   Continent [6]
    Rank CCA3  Country.Territory     Capital          Continent X2022.Population
   <int> <chr> <chr>                 <chr>            <chr>                <int>
 1    36 AFG   ""                    Kabul            Asia              41128771
 2   138 ALB   "Albania"             Tirana           Europe             2842321
 3    34 DZA   "Algeria"             Algiers          Africa            44903225
 4   213 ASM   "American Samoa"      Pago Pago        Oceania              44273
 5   203 AND   "Andorra"             Andorra la Vella Europe               79824
 6    42 AGO   "Angola"              Luanda           Africa            35588987
 7   224 AIA   "Anguilla"            The Valley       North Am…            15857
 8   201 ATG   "Antigua and Barbuda" Saint John’s     North Am…            93763
 9    33 ARG   "Argentina"           Buenos Aires     South Am…         45510318
10   140 ARM   "Armenia"             Yerevan          Asia               2780469
# ℹ 224 more rows
# ℹ 11 more variables: X2020.Population <int>, X2015.Population <int>,
#   X2010.Population <int>, X2000.Population <int>, X1990.Population <int>,
#   X1980.Population <int>, X1970.Population <int>, Area..km.. <int>,
#   Density..per.km.. <dbl>, Growth.Rate <dbl>,
#   World.Population.Percentage <dbl>

In [2]:
library(dplyr)

data <- read.csv("world_population.csv")

#data <- matrix( c('a','a','b','c','b','a'), nrow=2,ncol=3,byrow = TRUE)
# data<-group_by(data,Continent)
# summarise(data, Mean.X2022.Population = mean(X2022.Population))
print(group_by(data,Continent))

# A tibble: 234 × 17
# Groups:   Continent [6]
    Rank CCA3  Country.Territory     Capital          Continent X2022.Population
   <int> <chr> <chr>                 <chr>            <chr>                <int>
 1    36 AFG   ""                    Kabul            Asia              41128771
 2   138 ALB   "Albania"             Tirana           Europe             2842321
 3    34 DZA   "Algeria"             Algiers          Africa            44903225
 4   213 ASM   "American Samoa"      Pago Pago        Oceania              44273
 5   203 AND   "Andorra"             Andorra la Vella Europe               79824
 6    42 AGO   "Angola"              Luanda           Africa            35588987
 7   224 AIA   "Anguilla"            The Valley       North Am…            15857
 8   201 ATG   "Antigua and Barbuda" Saint John’s     North Am…            93763
 9    33 ARG   "Argentina"           Buenos Aires     South Am…         45510318
10   140 ARM   "Armenia"             Yerevan          Asia               2780469
# ℹ 224 more rows
# ℹ 11 more variables: X2020.Population <int>, X2015.Population <int>,
#   X2010.Population <int>, X2000.Population <int>, X1990.Population <int>,
#   X1980.Population <int>, X1970.Population <int>, Area..km.. <int>,
#   Density..per.km.. <dbl>, Growth.Rate <dbl>,
#   World.Population.Percentage <dbl>

In [3]:
data <- read.csv("world_population.csv")

#data <- matrix( c('a','a','b','c','b','a'), nrow=2,ncol=3,byrow = TRUE)
data<-group_by(data,Continent)
summarise(data)

  Continent
1 Africa
2 Asia
3 Europe
4 North America
5 Oceania
6 South America

In [19]:
library(dplyr)
data <- read.csv("world_population.csv")
data2 <- read.csv("world_population - Copy.csv")
# merged_file <- merge(data, data2, by = "Rank")
merged_file <- merge(data, data2, by.x ="Rank1", by.y ="Rank2", all.y = TRUE)
write.csv(merged_file, "merged_file.csv")

In [1]:
library(dplyr)
data <- read.csv("world_population.csv")
data <- arrange(data, Rank1)
# summary(data)
# pop_2022 <- select(data, Rank1)
# plot(pop_2022)
x<-1:234
y<- data$Rank
plot(x,y, main="Rank Plot", xlab = "Rank", ylab = "Rank Y")

Attaching package: ‘dplyr’


The following objects are masked from ‘package:stats’:

    filter, lag


The following objects are masked from ‘package:base’:

    intersect, setdiff, setequal, union


Warning message in file(file, "rt"):
“cannot open file 'world_population.csv': No such file or directory”

ERROR: Error in file(file, "rt"): cannot open the connection